language: node_js
node_js:
  - "v8.10.0"
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiterdb
before_script:
  - psql -c 'CREATE DATABASE waiterdb;' -U postgres
  - psql -U postgres -d waiterdb -a -f tables.sql
